blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/tmoricrif/skills-expand-your-team-with-copilot/discussions
    about: Have a question? Start a discussion instead of opening an issue.
