name: Modify Activity Details
description: Request changes to an existing activity's schedule, description, or capacity
title: "[Modify Activity]: "
labels: ["enhancement", "activity"]
body:
  - type: markdown
    attributes:
      value: |
        ## Modify an Existing Activity
        Use this form to request changes to an existing activity. Fill out only the fields you want to change.

  - type: dropdown
    id: activity-name
    attributes:
      label: Which Activity?
      description: Select the activity you want to modify
      options:
        - Chess Club
        - Programming Class
        - Morning Fitness
        - Soccer Team
        - Basketball Team
        - Art Club
        - Drama Club
        - Math Club
        - Debate Team
        - Weekend Robotics Workshop
        - Science Olympiad
        - Sunday Chess Tournament
        - Manga Maniacs
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: other-activity
    attributes:
      label: Other Activity Name
      description: If you selected "Other" above, specify the activity name
      placeholder: Enter the exact activity name
    validations:
      required: false

  - type: checkboxes
    id: what-to-change
    attributes:
      label: What needs to be changed?
      description: Select all that apply
      options:
        - label: Description
        - label: Schedule (days or times)
        - label: Maximum participants
        - label: Activity name

  - type: textarea
    id: new-description
    attributes:
      label: New Description (if applicable)
      description: Provide the updated activity description
      placeholder: Leave blank if not changing
    validations:
      required: false

  - type: dropdown
    id: new-days
    attributes:
      label: New Meeting Days (if applicable)
      description: Select the new day(s) of the week
      multiple: true
      options:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
    validations:
      required: false

  - type: input
    id: new-start-time
    attributes:
      label: New Start Time (if applicable)
      description: Use 24-hour format
      placeholder: "e.g., 15:30 for 3:30 PM"
    validations:
      required: false

  - type: input
    id: new-end-time
    attributes:
      label: New End Time (if applicable)
      description: Use 24-hour format
      placeholder: "e.g., 17:00 for 5:00 PM"
    validations:
      required: false

  - type: input
    id: new-max-participants
    attributes:
      label: New Maximum Participants (if applicable)
      description: Enter the new participant limit
      placeholder: "e.g., 25"
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why is this change needed?
      placeholder: Explain the reason for these modifications
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Acceptance Criteria
        - The activity details should be updated in the database
        - Changes should be visible on the website immediately after implementation
        - All existing student registrations should remain intact
        - The activity should still be filterable by the new schedule criteria
        
        ### Implementation Hints
        - Locate the activity in the `initial_activities` dictionary in `src/backend/database.py`
        - Update only the specified fields
        - Ensure the `schedule` string matches the `schedule_details` structure
        - If the database is already initialized, you may need to update the live database or provide migration instructions
