name: New Feature Request
description: Suggest a new capability for the system
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Suggest a New Feature
        Help us improve the system by suggesting new capabilities or functionality.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Description
      description: What new feature would you like to see?
      placeholder: "Example: Add the ability to export the participant list for each activity"
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: What problem does this solve?
      description: Explain why this feature is needed
      placeholder: "Example: Right now I have to manually write down all participants. An export feature would save time."
    validations:
      required: true

  - type: textarea
    id: how-it-works
    attributes:
      label: How should it work?
      description: Describe how you imagine using this feature
      placeholder: |
        Example:
        1. Click on an activity
        2. Click an "Export" button
        3. Download a file with all student names and emails
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Who would use this feature?
      description: Who benefits from this feature?
      multiple: true
      options:
        - Teachers
        - Students
        - Administrators
        - Parents
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this?
      description: How much would this improve your experience?
      options:
        - Critical - Can't work without it
        - High - Would make things much easier
        - Medium - Nice to have
        - Low - Small improvement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Current Workaround
      description: How do you handle this need right now?
      placeholder: "Example: I currently take screenshots of the participant lists"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Details
      description: Any other information about this feature?
      placeholder: Examples from other systems, specific requirements, etc.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### Acceptance Criteria
        - The feature should work as described
        - The feature should be easy to use without technical knowledge
        - The feature should not interfere with existing functionality
        - The feature should be tested with real-world scenarios
        
        ### Implementation Considerations
        - Consider whether this requires:
          - New API endpoints (backend changes in `src/backend/routers/`)
          - New UI elements (frontend changes in `src/static/`)
          - Database schema changes (updates to `src/backend/database.py`)
          - New dependencies (update `src/requirements.txt`)
        - Think about edge cases and error handling
        - Consider security implications (authentication, data validation)
        - Plan for scalability and performance
        - Keep the implementation simple and maintainable
